# Generated by Django 5.2.15 on 2026-07-02 07:57

from django.db import migrations

DEFAULT_FIELD_COUNT = 14


def offset_question_positions(apps, schema_editor):
    ExhibitionQuestion = apps.get_model("exhibition", "ExhibitionQuestion")
    event_ids = ExhibitionQuestion.objects.values_list("event_id", flat=True).distinct()
    for event_id in event_ids:
        questions = list(ExhibitionQuestion.objects.filter(event_id=event_id).order_by("position", "id"))
        for index, question in enumerate(questions):
            question.position = DEFAULT_FIELD_COUNT + index
        ExhibitionQuestion.objects.bulk_update(questions, ["position"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_exhibitorsettings_proposal_field_settings'),
    ]

    operations = [
        migrations.RunPython(offset_question_positions, noop),
    ]
