# Generated by Django 5.2.15 on 2026-07-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_sendmail_from_plugins'),
        ('exhibition', '0007_offset_exhibition_question_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionEmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('locale', models.CharField(blank=True, default='', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_email_queue', to='base.event')),
                ('exhibitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='exhibition.exhibitorinfo')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='exhibition.exhibitionproposal')),
            ],
            options={
                'verbose_name': 'Queued email',
                'verbose_name_plural': 'Queued emails',
                'ordering': ('-created',),
            },
        ),
    ]
