# Generated by Django 5.2.15 on 2026-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_exhibitionemailqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorinfo',
            name='exhibitor_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitorinfo',
            name='sponsor_position',
            field=models.IntegerField(default=0),
        ),
    ]
