# Generated by Django 5.2.15 on 2026-07-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0009_exhibitionproposal_profile_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitorinfo",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
