# Generated by Django 5.2.15 on 2026-07-21 15:46

import exhibition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0011_default_share_attendee_name_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exhibitorsettings",
            name="call_secret",
            field=models.CharField(default=exhibition.models.generate_call_secret, max_length=64),
        ),
    ]
