# Generated by Django 5.2.15 on 2026-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0012_exhibitorsettings_call_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionemailqueue',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
