import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exhibition", "0024_voucher_email_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibitorinfo",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="exhibitorinfo",
            name="header_image_url",
        ),
        migrations.RemoveField(
            model_name="exhibitionproposal",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="exhibitionproposal",
            name="header_image_url",
        ),
        migrations.AlterField(
            model_name="exhibitorinfo",
            name="sponsor_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="exhibition.sponsorgroup",
            ),
        ),
        migrations.RenameField(
            model_name="exhibitorinfo",
            old_name="header_image",
            new_name="banner",
        ),
        migrations.RenameField(
            model_name="exhibitionproposal",
            old_name="header_image",
            new_name="banner",
        ),
        migrations.RenameModel(
            old_name="ExhibitionProposal",
            new_name="ExhibitionRequest",
        ),
        migrations.RenameModel(
            old_name="ExhibitionProposalSocialLink",
            new_name="ExhibitionRequestSocialLink",
        ),
        migrations.RenameModel(
            old_name="ExhibitionProposalExtraLink",
            new_name="ExhibitionRequestExtraLink",
        ),
        migrations.RenameField(
            model_name="exhibitorsettings",
            old_name="proposal_field_settings",
            new_name="request_field_settings",
        ),
        migrations.RenameField(
            model_name="exhibitionrequestsociallink",
            old_name="proposal",
            new_name="exhibition_request",
        ),
        migrations.RenameField(
            model_name="exhibitionrequestextralink",
            old_name="proposal",
            new_name="exhibition_request",
        ),
        migrations.RenameField(
            model_name="exhibitionanswer",
            old_name="proposal",
            new_name="exhibition_request",
        ),
        migrations.RenameField(
            model_name="exhibitionemailqueue",
            old_name="proposal",
            new_name="exhibition_request",
        ),
        migrations.AlterField(
            model_name="exhibitionrequest",
            name="approved_exhibitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_requests",
                to="exhibition.exhibitorinfo",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionrequest",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exhibition_requests",
                to="base.event",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionrequest",
            name="sponsor_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exhibition_requests",
                to="exhibition.sponsorgroup",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exhibition_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
